name: Intelligence.AI SchemaHub

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_type }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    env:
      KRAFTCLOUD_REGION: was1
      KRAFTKIT_VERSION: 0.9.0
    steps:
      - uses: intelligence-ai/jsonschema@v2.6.0
      - uses: actions/checkout@v4
      - run: make
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update schema cache'
          add: '.cache'

      - name: Install KraftKit
        run: |
          wget https://github.com/unikraft/kraftkit/releases/download/v${{ env.KRAFTKIT_VERSION }}/kraftkit_${{ env.KRAFTKIT_VERSION }}_linux_amd64.deb
          sudo dpkg -i kraftkit_${{ env.KRAFTKIT_VERSION }}_linux_amd64.deb
          rm kraftkit_${{ env.KRAFTKIT_VERSION }}_linux_amd64.deb
          kraft version
          docker run --rm -d --name buildkit --privileged moby/buildkit:latest
          kraft login --token ${{ secrets.KRAFTCLOUD_TOKEN }} index.unikraft.io

      - uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SCHEMAHUB_ACCESS_TOKEN }}

      - run: >
          kraft pkg
          --no-prompt
          --kraftfile Kraftfile
          --buildkit-host "docker-container://buildkit"
          --plat kraftcloud
          --push
          --name index.unikraft.io/sourcemeta/schemas:latest

      - run: >
          kraft cloud instance create
          --no-prompt
          --rollout remove
          --replicas 2
          --restart on-failure
          --start
          --wait-for-image
          --service-group schemahub
          --log-type=basic
          --metro ${{ env.KRAFTCLOUD_REGION }}
          sourcemeta/schemas:latest
        env:
          KRAFTCLOUD_TOKEN: ${{ secrets.KRAFTCLOUD_TOKEN }}
          KRAFTCLOUD_USER: ${{ secrets.KRAFTCLOUD_USER }}
