name: Intelligence.AI SchemaHub

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_type }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:
      - uses: intelligence-ai/jsonschema@v2.6.0
      - uses: actions/checkout@v4
      - run: make
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update schema cache'
          add: '.cache'
      - uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
