name: Intelligence.AI SchemaHub

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_type }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    env:
      KRAFTCLOUD_REGION: was1
      KRAFTKIT_VERSION: 0.9.0
    steps:
      - uses: intelligence-ai/jsonschema@v2.6.0
      - uses: actions/checkout@v4
      - run: make
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update schema cache'
          add: '.cache'

      - uses: unikraft/kraftkit@staging
        with:
          auths: |
            ghcr.io:
              user: ${{ github.actor }}
              token: ${{ secrets.SCHEMAHUB_ACCESS_TOKEN }}
          run: >
            kraft pkg \
              --no-prompt \
              --kraftfile Kraftfile \
              --buildkit-host "docker-container://buildkit" \
              --plat kraftcloud \
              --push \
              --name index.unikraft.io/sourcemeta/schemas:latest
        env:
          KRAFTCLOUD_TOKEN: ${{ secrets.KRAFTCLOUD_TOKEN }}
