name: Intelligence.AI SchemaHub

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: intelligence-ai/jsonschema@v2.6.0
      - uses: actions/checkout@v4
      - run: make
      - run: ./scripts/no-uncommitted-changes.sh
